'use strict'

const CAPABILITIES = [
  [
    'notion.activate',
    'write',
    'canonical_preview_apply',
    'personal_only',
    'notion-activation-v1',
    'canonical-receipt-v1',
  ],
  [
    'organization.assign_project',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'task-v1',
    'canonical-receipt-v1',
  ],
  ['organization.inventory', 'read', 'none', 'personal_or_active_workspace', 'organization-inventory-v1', null],
  [
    'organization.set_canvas_group',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'task-v1',
    'canonical-receipt-v1',
  ],
  ['recurrence.chain', 'read', 'none', 'personal_or_active_workspace', 'task-v1', null],
  [
    'recurrence.edit_future',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'task-v1',
    'canonical-receipt-v1',
  ],
  [
    'recurrence.end_series',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'task-v1',
    'canonical-receipt-v1',
  ],
  [
    'recurrence.pause',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'task-v1',
    'canonical-receipt-v1',
  ],
  [
    'recurrence.resume',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'task-v1',
    'canonical-receipt-v1',
  ],
  [
    'subtask.batch',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'task-v1',
    'canonical-receipt-v1',
  ],
  ['subtask.inventory', 'read', 'none', 'personal_or_active_workspace', 'task-v1', null],
  [
    'task.complete',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'task-v1',
    'canonical-receipt-v1',
  ],
  [
    'task.done_for_now',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'task-v1',
    'canonical-receipt-v1',
  ],
  ['task.inventory', 'read', 'none', 'personal_or_active_workspace', 'task-inventory-v1', null],
  [
    'task.lifecycle.create',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'task-v1',
    'canonical-receipt-v1',
  ],
  [
    'task.lifecycle.delete',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'task-v1',
    'canonical-receipt-v1',
  ],
  [
    'task.lifecycle.reopen',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'task-v1',
    'canonical-receipt-v1',
  ],
  [
    'task.lifecycle.restore',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'task-v1',
    'canonical-receipt-v1',
  ],
  ['task.merge', 'write', 'canonical_preview_apply', 'personal_or_active_workspace', 'task-v1', 'canonical-receipt-v1'],
  ['task.patch', 'write', 'canonical_preview_apply', 'personal_or_active_workspace', 'task-v1', 'canonical-receipt-v1'],
  [
    'timer.extend',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'timer-v1',
    'canonical-receipt-v1',
  ],
  [
    'timer.pause',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'timer-v1',
    'canonical-receipt-v1',
  ],
  [
    'timer.resume',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'timer-v1',
    'canonical-receipt-v1',
  ],
  ['timer.session', 'read', 'none', 'personal_or_active_workspace', 'timer-v1', null],
  [
    'timer.start',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'timer-v1',
    'canonical-receipt-v1',
  ],
  [
    'timer.stop',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'timer-v1',
    'canonical-receipt-v1',
  ],
  [
    'timer.switch_task',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'timer-v1',
    'canonical-receipt-v1',
  ],
  [
    'work_block.batch',
    'write',
    'canonical_preview_apply',
    'personal_or_active_workspace',
    'task-v1',
    'canonical-receipt-v1',
  ],
  ['work_block.inventory', 'read', 'none', 'personal_or_active_workspace', 'task-v1', null],
].map(([id, mode, approval, scope, contractVersion, receiptVersion]) => ({
  id,
  mode,
  approval,
  scope,
  contractVersion,
  receiptVersion,
}))

const MANIFEST = {
  manifestVersion: 'assistant-capabilities-v1',
  capabilities: CAPABILITIES,
}

function getCapabilityManifest() {
  return JSON.parse(JSON.stringify(MANIFEST))
}

module.exports = { getCapabilityManifest }
