-- Canonical transactional recurring-task "Done for now" operation.
-- The living task is advanced while an immutable completion snapshot is kept.

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.flowstate_action_receipts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  workspace_id uuid REFERENCES public.workspaces(id) ON DELETE CASCADE,
  operation text NOT NULL,
  request_id text NOT NULL,
  payload_hash text NOT NULL,
  preview_version text NOT NULL,
  receipt jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, operation, request_id)
);

ALTER TABLE public.flowstate_action_receipts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "action_receipts_select_own"
  ON public.flowstate_action_receipts;
CREATE POLICY "action_receipts_select_own"
  ON public.flowstate_action_receipts
  FOR SELECT
  USING (auth.uid() = user_id);

REVOKE ALL ON public.flowstate_action_receipts FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.flowstate_action_receipts TO authenticated;

COMMENT ON TABLE public.flowstate_action_receipts IS
  'User-scoped idempotency receipts for approval-gated FlowState domain operations.';

-- Completion snapshots and living occurrences intentionally share the same
-- parent/count pair. Keep each side unique without making them collide.
DROP INDEX IF EXISTS public.idx_unique_recurrence_occurrence;

CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_living_recurrence_occurrence
  ON public.tasks (recurrence_parent_id, recurrence_count)
  WHERE recurrence_parent_id IS NOT NULL
    AND recurrence_count IS NOT NULL
    AND is_deleted = false
    AND COALESCE(is_completion_record, false) = false;

CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_completed_recurrence_occurrence
  ON public.tasks (recurrence_parent_id, recurrence_count)
  WHERE recurrence_parent_id IS NOT NULL
    AND recurrence_count IS NOT NULL
    AND is_deleted = false
    AND is_completion_record = true;

CREATE OR REPLACE FUNCTION public.flowstate_next_recurrence_date(
  p_current_due date,
  p_rule jsonb,
  p_next_count integer
)
RETURNS date
LANGUAGE plpgsql
IMMUTABLE
SET search_path = public
AS $$
DECLARE
  v_pattern text := p_rule->>'pattern';
  v_interval integer;
  v_next date;
  v_target_month date;
  v_original_day integer;
  v_month_day integer;
  v_days_in_month integer;
  v_current_dow integer;
  v_first_dow integer;
  v_next_dow integer;
  v_nth integer;
  v_weekday integer;
BEGIN
  IF p_current_due IS NULL OR p_rule IS NULL OR jsonb_typeof(p_rule) <> 'object' THEN
    RETURN NULL;
  END IF;

  IF p_rule->>'endType' = 'after_count'
     AND p_rule ? 'endCount'
     AND p_next_count >= (p_rule->>'endCount')::integer THEN
    RETURN NULL;
  END IF;

  v_interval := COALESCE((p_rule->>'interval')::integer, 1);
  IF v_interval < 1 THEN
    RETURN NULL;
  END IF;

  CASE v_pattern
    WHEN 'daily' THEN
      v_next := p_current_due + v_interval;

    WHEN 'weekly' THEN
      IF jsonb_typeof(p_rule->'weekdays') = 'array'
         AND jsonb_array_length(p_rule->'weekdays') > 0 THEN
        v_current_dow := extract(dow FROM p_current_due)::integer;

        SELECT min(value::integer), min(value::integer) FILTER (WHERE value::integer > v_current_dow)
          INTO v_first_dow, v_next_dow
        FROM jsonb_array_elements_text(p_rule->'weekdays');

        IF v_first_dow NOT BETWEEN 0 AND 6
           OR EXISTS (
             SELECT 1 FROM jsonb_array_elements_text(p_rule->'weekdays') d(value)
             WHERE value::integer NOT BETWEEN 0 AND 6
           ) THEN
          RETURN NULL;
        END IF;

        IF v_next_dow IS NOT NULL THEN
          v_next := p_current_due + (v_next_dow - v_current_dow);
        ELSE
          v_next := p_current_due + (7 * v_interval - v_current_dow + v_first_dow);
        END IF;
      ELSE
        v_next := p_current_due + (7 * v_interval);
      END IF;

    WHEN 'monthly' THEN
      v_original_day := extract(day FROM p_current_due)::integer;
      v_target_month := date_trunc('month', p_current_due)::date
                        + make_interval(months => v_interval);
      v_days_in_month := extract(
        day FROM (v_target_month + interval '1 month - 1 day')
      )::integer;

      IF p_rule ? 'monthDay' THEN
        v_month_day := (p_rule->>'monthDay')::integer;
        IF v_month_day < 1 THEN
          RETURN NULL;
        END IF;
        v_next := v_target_month + (least(v_month_day, v_days_in_month) - 1);
      ELSIF jsonb_typeof(p_rule->'monthWeekday') = 'object' THEN
        v_nth := (p_rule #>> '{monthWeekday,nth}')::integer;
        v_weekday := (p_rule #>> '{monthWeekday,day}')::integer;
        IF v_weekday NOT BETWEEN 0 AND 6 OR (v_nth <> -1 AND v_nth < 1) THEN
          RETURN NULL;
        END IF;

        v_next := v_target_month
          + ((v_weekday - extract(dow FROM v_target_month)::integer + 7) % 7);
        IF v_nth = -1 THEN
          v_next := v_next + ((v_days_in_month - extract(day FROM v_next)::integer) / 7) * 7;
        ELSE
          v_next := v_next + (v_nth - 1) * 7;
        END IF;
      ELSE
        v_next := v_target_month + (least(v_original_day, v_days_in_month) - 1);
      END IF;

    WHEN 'yearly' THEN
      -- Building from the target year's first day avoids Feb 29 overflowing.
      v_target_month := make_date(
        extract(year FROM p_current_due)::integer + v_interval,
        extract(month FROM p_current_due)::integer,
        1
      );
      v_days_in_month := extract(
        day FROM (date_trunc('month', v_target_month) + interval '1 month - 1 day')
      )::integer;
      v_next := v_target_month
                + (least(extract(day FROM p_current_due)::integer, v_days_in_month) - 1);

    ELSE
      RETURN NULL;
  END CASE;

  IF p_rule->>'endType' = 'on_date'
     AND nullif(p_rule->>'endDate', '') IS NOT NULL
     AND v_next > (p_rule->>'endDate')::date THEN
    RETURN NULL;
  END IF;

  RETURN v_next;
END;
$$;

REVOKE ALL ON FUNCTION public.flowstate_next_recurrence_date(date, jsonb, integer)
  FROM PUBLIC, anon, authenticated;

DROP FUNCTION IF EXISTS public.flowstate_done_for_now(text, boolean, date, text, text);
DROP FUNCTION IF EXISTS public.flowstate_done_for_now(text, boolean, date, text, text, uuid);

CREATE OR REPLACE FUNCTION public.flowstate_done_for_now(
  p_task_id text,
  p_preview boolean DEFAULT true,
  p_next_due_date date DEFAULT NULL,
  p_request_id text DEFAULT NULL,
  p_preview_version text DEFAULT NULL,
  p_workspace_id uuid DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_actor uuid := auth.uid();
  v_task public.tasks%ROWTYPE;
  v_existing_receipt public.flowstate_action_receipts%ROWTYPE;
  v_payload_hash text;
  v_preview_version text;
  v_parent_id public.tasks.id%TYPE;
  v_current_due date;
  v_next_due date;
  v_next_due_timestamp timestamptz;
  v_next_count integer;
  v_completion_id public.tasks.id%TYPE := gen_random_uuid();
  v_next_instance_id text := gen_random_uuid()::text;
  v_current_instance jsonb;
  v_completion_instances jsonb := '[]'::jsonb;
  v_next_instances jsonb;
  v_reset_subtasks jsonb;
  v_now timestamptz := clock_timestamp();
  v_receipt jsonb;
BEGIN
  IF v_actor IS NULL THEN
    RETURN jsonb_build_object(
      'ok', false,
      'error', jsonb_build_object('code', 'not_authenticated', 'message', 'Authentication is required')
    );
  END IF;

  IF nullif(btrim(p_task_id), '') IS NULL THEN
    RETURN jsonb_build_object(
      'ok', false,
      'error', jsonb_build_object('code', 'invalid_request', 'message', 'Exact task id is required')
    );
  END IF;

  IF NOT p_preview
     AND (nullif(btrim(p_request_id), '') IS NULL
          OR nullif(btrim(p_preview_version), '') IS NULL) THEN
    RETURN jsonb_build_object(
      'ok', false,
      'error', jsonb_build_object(
        'code', 'approval_receipt_required',
        'message', 'requestId and previewVersion are required for apply'
      )
    );
  END IF;

  v_payload_hash := encode(
    digest(
      convert_to(
        jsonb_build_object(
          'taskId', p_task_id,
          'workspaceId', p_workspace_id,
          'nextDueDate', p_next_due_date,
          'previewVersion', p_preview_version
        )::text,
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );

  -- A retry must be resolved before examining the now-advanced living task.
  IF NOT p_preview THEN
    SELECT * INTO v_existing_receipt
    FROM public.flowstate_action_receipts
    WHERE user_id = v_actor
      AND operation = 'done_for_now'
      AND request_id = btrim(p_request_id);

    IF FOUND THEN
      IF v_existing_receipt.payload_hash <> v_payload_hash THEN
        RETURN jsonb_build_object(
          'ok', false,
          'error', jsonb_build_object(
            'code', 'idempotency_conflict',
            'message', 'requestId was already used with a different payload'
          )
        );
      END IF;
      RETURN v_existing_receipt.receipt;
    END IF;
  END IF;

  IF p_preview THEN
    SELECT * INTO v_task
    FROM public.tasks
    WHERE id::text = p_task_id AND is_deleted = false;
  ELSE
    SELECT * INTO v_task
    FROM public.tasks
    WHERE id::text = p_task_id AND is_deleted = false
    FOR UPDATE;
  END IF;

  IF NOT FOUND
     OR (
       v_task.workspace_id IS NULL
       AND (p_workspace_id IS NOT NULL OR v_task.user_id <> v_actor)
     )
     OR (
       v_task.workspace_id IS NOT NULL
       AND (
         p_workspace_id IS DISTINCT FROM v_task.workspace_id
         OR (
           NOT EXISTS (
         SELECT 1 FROM public.workspace_members
         WHERE workspace_id = v_task.workspace_id AND user_id = v_actor
           )
           AND NOT EXISTS (
             SELECT 1 FROM public.workspaces
             WHERE id = v_task.workspace_id AND owner_id = v_actor
           )
         )
       )
     ) THEN
    RETURN jsonb_build_object(
      'ok', false,
      'error', jsonb_build_object('code', 'not_found', 'message', 'Recurring task was not found')
    );
  END IF;

  -- The task lock may have waited for an identical apply to commit. Resolve
  -- that retry before deriving state from the already-advanced living task.
  IF NOT p_preview THEN
    SELECT * INTO v_existing_receipt
    FROM public.flowstate_action_receipts
    WHERE user_id = v_actor
      AND operation = 'done_for_now'
      AND request_id = btrim(p_request_id);

    IF FOUND THEN
      IF v_existing_receipt.payload_hash <> v_payload_hash THEN
        RETURN jsonb_build_object(
          'ok', false,
          'error', jsonb_build_object(
            'code', 'idempotency_conflict',
            'message', 'requestId was already used with a different payload'
          )
        );
      END IF;
      RETURN v_existing_receipt.receipt;
    END IF;
  END IF;

  IF v_task.recurrence_rule IS NULL OR v_task.is_completion_record = true THEN
    RETURN jsonb_build_object(
      'ok', false,
      'error', jsonb_build_object('code', 'not_recurring', 'message', 'Task is not an active recurring task')
    );
  END IF;

  v_parent_id := COALESCE(v_task.recurrence_parent_id, v_task.id);
  v_current_due := COALESCE(v_task.due_date::date, v_task.scheduled_date::date, CURRENT_DATE);
  v_next_count := COALESCE(v_task.recurrence_count, 0) + 1;

  IF EXISTS (
    SELECT 1 FROM public.tasks
    WHERE recurrence_parent_id = v_parent_id
      AND recurrence_count = COALESCE(v_task.recurrence_count, 0)
      AND is_completion_record = true
      AND is_deleted = false
  ) THEN
    RETURN jsonb_build_object(
      'ok', false,
      'error', jsonb_build_object(
        'code', 'already_completed',
        'message', 'The current recurring occurrence is already completed'
      )
    );
  END IF;

  IF p_next_due_date IS NOT NULL THEN
    IF p_next_due_date <= v_current_due THEN
      RETURN jsonb_build_object(
        'ok', false,
        'error', jsonb_build_object(
          'code', 'invalid_next_date',
          'message', 'Next due date must be later than the completed occurrence'
        )
      );
    END IF;
    IF v_task.recurrence_rule->>'endType' = 'after_count'
       AND v_task.recurrence_rule ? 'endCount'
       AND v_next_count >= (v_task.recurrence_rule->>'endCount')::integer THEN
      RETURN jsonb_build_object(
        'ok', false,
        'error', jsonb_build_object(
          'code', 'recurrence_exhausted',
          'message', 'The recurrence rule does not permit another occurrence'
        )
      );
    END IF;
    IF v_task.recurrence_rule->>'endType' = 'on_date'
       AND nullif(v_task.recurrence_rule->>'endDate', '') IS NOT NULL
       AND p_next_due_date > (v_task.recurrence_rule->>'endDate')::date THEN
      RETURN jsonb_build_object(
        'ok', false,
        'error', jsonb_build_object(
          'code', 'invalid_next_date',
          'message', 'Next due date is beyond the recurrence end date'
        )
      );
    END IF;
    v_next_due := p_next_due_date;
  ELSE
    BEGIN
      v_next_due := public.flowstate_next_recurrence_date(
        v_current_due,
        v_task.recurrence_rule,
        v_next_count
      );
    EXCEPTION WHEN OTHERS THEN
      RETURN jsonb_build_object(
        'ok', false,
        'error', jsonb_build_object(
          'code', 'recurrence_calculation_failed',
          'message', 'The next recurring occurrence could not be calculated'
        )
      );
    END;
  END IF;

  IF v_next_due IS NULL THEN
    RETURN jsonb_build_object(
      'ok', false,
      'error', jsonb_build_object(
        'code', 'recurrence_exhausted',
        'message', 'The recurrence rule does not produce another occurrence'
      )
    );
  END IF;

  v_preview_version := encode(
    digest(
      convert_to(
        jsonb_build_object(
          'taskId', v_task.id,
          'workspaceId', v_task.workspace_id,
          'updatedAt', v_task.updated_at,
          'dueDate', v_current_due,
          'nextDueDate', v_next_due,
          'recurrenceRule', v_task.recurrence_rule,
          'recurrenceCount', COALESCE(v_task.recurrence_count, 0),
          'instances', COALESCE(v_task.instances, '[]'::jsonb)
        )::text,
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );

  IF p_preview THEN
    RETURN jsonb_build_object(
      'ok', true,
      'preview', true,
      'previewVersion', v_preview_version,
      'task', jsonb_build_object(
        'id', v_task.id,
        'title', v_task.title,
        'workspaceId', v_task.workspace_id
      ),
      'currentOccurrence', jsonb_build_object(
        'dueDate', v_current_due,
        'statusBefore', CASE WHEN v_task.status = 'done' THEN 'done' ELSE 'todo' END,
        'statusAfter', 'done'
      ),
      'recurrence', jsonb_build_object(
        'nextDueDateBefore', null,
        'nextDueDateAfter', v_next_due,
        'nextDateSource', CASE WHEN p_next_due_date IS NULL THEN 'rule' ELSE 'override' END,
        'cadencePreserved', true,
        'countBefore', COALESCE(v_task.recurrence_count, 0),
        'countAfter', v_next_count,
        'rule', v_task.recurrence_rule
      ),
      'willWrite', jsonb_build_array(
        'current occurrence completion',
        'completion history',
        'next occurrence schedule'
      )
    );
  END IF;

  IF p_preview_version <> v_preview_version THEN
    RETURN jsonb_build_object(
      'ok', false,
      'error', jsonb_build_object(
        'code', 'state_conflict',
        'message', 'Task changed after preview; preview the operation again'
      )
    );
  END IF;

  SELECT value INTO v_current_instance
  FROM jsonb_array_elements(COALESCE(v_task.instances, '[]'::jsonb)) AS occurrence(value)
  WHERE value->>'scheduledDate' = v_current_due::text
  LIMIT 1;

  SELECT COALESCE(
    jsonb_agg(
      value || jsonb_build_object(
        'id', gen_random_uuid()::text,
        'taskId', v_completion_id,
        'status', 'completed',
        'updatedAt', v_now
      )
    ),
    '[]'::jsonb
  ) INTO v_completion_instances
  FROM jsonb_array_elements(COALESCE(v_task.instances, '[]'::jsonb)) AS occurrence(value)
  WHERE value->>'scheduledDate' = v_current_due::text;

  SELECT COALESCE(
    jsonb_agg(
      value || jsonb_build_object('isCompleted', false, 'updatedAt', v_now)
    ),
    '[]'::jsonb
  ) INTO v_reset_subtasks
  FROM jsonb_array_elements(COALESCE(v_task.subtasks, '[]'::jsonb)) AS subtask(value);

  v_next_instances := jsonb_build_array(
    jsonb_strip_nulls(jsonb_build_object(
      'id', v_next_instance_id,
      'taskId', v_task.id,
      'scheduledDate', v_next_due,
      'scheduledTime', COALESCE(v_current_instance->>'scheduledTime', v_task.due_time, v_task.scheduled_time),
      'duration', COALESCE(
        (v_current_instance->>'duration')::integer,
        v_task.estimated_duration,
        25
      ),
      'status', 'scheduled',
      'isRecurring', true,
      'createdAt', v_now,
      'updatedAt', v_now
    ))
  );

  v_next_due_timestamp := v_next_due::timestamp
    + COALESCE(v_task.due_date::time, time '00:00');

  INSERT INTO public.tasks (
    id, user_id, workspace_id, assigned_to, project_id,
    title, description, status, priority, progress,
    total_pomodoros, estimated_pomodoros, completed_pomodoros,
    due_date, due_time, estimated_duration, subtasks, tags,
    instances, recurrence_rule, recurrence_parent_id, recurrence_count,
    is_completion_record, is_in_inbox, is_deleted, completed_at,
    scheduled_date, scheduled_time, is_uncategorized,
    notification_prefs, reminders, attachments, planning_notes,
    calendar_locked, lane_id, created_at, updated_at
  ) VALUES (
    v_completion_id, v_task.user_id, v_task.workspace_id, v_task.assigned_to, v_task.project_id,
    v_task.title, v_task.description, 'done', v_task.priority, 100,
    v_task.total_pomodoros, v_task.estimated_pomodoros, v_task.completed_pomodoros,
    v_task.due_date, v_task.due_time, v_task.estimated_duration, v_task.subtasks, v_task.tags,
    v_completion_instances, null, v_parent_id, COALESCE(v_task.recurrence_count, 0),
    true, false, false, v_now,
    v_task.scheduled_date, v_task.scheduled_time, v_task.is_uncategorized,
    v_task.notification_prefs, v_task.reminders, v_task.attachments, v_task.planning_notes,
    v_task.calendar_locked, v_task.lane_id, v_now, v_now
  );

  UPDATE public.tasks
  SET status = 'planned',
      progress = 0,
      completed_at = null,
      due_date = v_next_due_timestamp,
      scheduled_date = v_next_due_timestamp,
      recurrence_parent_id = v_parent_id,
      recurrence_count = v_next_count,
      instances = v_next_instances,
      subtasks = v_reset_subtasks,
      parent_task_id = null,
      position = null,
      is_in_inbox = true,
      done_for_now_until = v_next_due,
      updated_at = v_now
  WHERE id = v_task.id;

  v_receipt := jsonb_build_object(
    'ok', true,
    'preview', false,
    'requestId', btrim(p_request_id),
    'previewVersion', v_preview_version,
    'taskId', v_task.id,
    'currentOccurrence', jsonb_build_object(
      'dueDate', v_current_due,
      'status', 'done'
    ),
    'completedOccurrence', jsonb_build_object(
      'id', v_completion_id,
      'status', 'done',
      'dueDate', v_current_due,
      'completedAt', v_now
    ),
    'nextOccurrence', jsonb_build_object(
      'id', v_next_instance_id,
      'taskId', v_task.id,
      'status', 'todo',
      'dueDate', v_next_due,
      'scheduledTime', v_next_instances #>> '{0,scheduledTime}',
      'duration', (v_next_instances #>> '{0,duration}')::integer
    ),
    'recurrence', jsonb_build_object(
      'active', true,
      'count', v_next_count,
      'rule', v_task.recurrence_rule
    )
  );

  INSERT INTO public.flowstate_action_receipts (
    user_id, workspace_id, operation, request_id,
    payload_hash, preview_version, receipt
  ) VALUES (
    v_actor, v_task.workspace_id, 'done_for_now', btrim(p_request_id),
    v_payload_hash, v_preview_version, v_receipt
  );

  RETURN v_receipt;
END;
$$;

REVOKE ALL ON FUNCTION public.flowstate_done_for_now(text, boolean, date, text, text, uuid)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.flowstate_done_for_now(text, boolean, date, text, text, uuid)
  TO authenticated;

COMMENT ON FUNCTION public.flowstate_done_for_now(text, boolean, date, text, text, uuid) IS
  'Previews or atomically completes one recurring occurrence, preserves history, and advances the living task exactly once.';
