-- TASK-1944: canonical task operation, revision, receipt, and change cursor.
--
-- Compatibility triggers are installed before callers migrate to the RPC so
-- legacy task writers immediately receive revisions and durable change events.

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

ALTER TABLE public.tasks
  ADD COLUMN IF NOT EXISTS canonical_revision bigint NOT NULL DEFAULT 1
  CHECK (canonical_revision > 0);

CREATE SEQUENCE IF NOT EXISTS public.change_sequence AS bigint;

CREATE TABLE IF NOT EXISTS public.canonical_operations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  operation_id text NOT NULL CHECK (char_length(operation_id) BETWEEN 1 AND 160),
  contract_version text NOT NULL CHECK (char_length(contract_version) BETWEEN 1 AND 64),
  source text NOT NULL CHECK (char_length(source) BETWEEN 1 AND 64),
  scope_kind text NOT NULL CHECK (scope_kind IN ('personal', 'workspace')),
  scope_id text NOT NULL,
  workspace_id uuid,
  entity_type text NOT NULL,
  action text NOT NULL,
  entity_id text NOT NULL,
  request_hash text NOT NULL,
  state text NOT NULL CHECK (state IN ('applying', 'committed')),
  canonical_revision bigint,
  change_sequence bigint,
  canonical_result jsonb,
  error_metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  committed_at timestamptz,
  UNIQUE (user_id, operation_id)
);

CREATE INDEX IF NOT EXISTS canonical_operations_entity_idx
  ON public.canonical_operations (user_id, entity_type, entity_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.canonical_operation_previews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  operation_id text NOT NULL CHECK (char_length(operation_id) BETWEEN 1 AND 160),
  preview_digest text NOT NULL,
  request_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (user_id, operation_id),
  UNIQUE (user_id, preview_digest)
);

CREATE TABLE IF NOT EXISTS public.canonical_change_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  change_sequence bigint NOT NULL DEFAULT nextval('public.change_sequence') UNIQUE,
  user_id uuid NOT NULL,
  actor_user_id uuid,
  workspace_id uuid,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  action text NOT NULL CHECK (action IN ('inserted', 'updated', 'deleted', 'restored')),
  canonical_revision bigint NOT NULL CHECK (canonical_revision > 0),
  operation_id text,
  source text NOT NULL,
  tombstone boolean NOT NULL DEFAULT false,
  projection jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX IF NOT EXISTS canonical_change_log_user_cursor_idx
  ON public.canonical_change_log (user_id, change_sequence);
CREATE INDEX IF NOT EXISTS canonical_change_log_workspace_cursor_idx
  ON public.canonical_change_log (workspace_id, change_sequence)
  WHERE workspace_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS canonical_change_log_entity_idx
  ON public.canonical_change_log (entity_type, entity_id, change_sequence DESC);
CREATE INDEX IF NOT EXISTS canonical_change_log_operation_idx
  ON public.canonical_change_log (operation_id)
  WHERE operation_id IS NOT NULL;

ALTER TABLE public.canonical_operations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.canonical_operation_previews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.canonical_change_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS canonical_operations_select_own
  ON public.canonical_operations;
CREATE POLICY canonical_operations_select_own
  ON public.canonical_operations
  FOR SELECT
  USING ((SELECT auth.uid()) = user_id);

REVOKE ALL ON public.canonical_operations FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.canonical_operation_previews FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.canonical_change_log FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.change_sequence FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.canonical_operations_id_seq FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.canonical_operation_previews_id_seq FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.canonical_change_log_id_seq FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.canonical_operations TO authenticated;
GRANT SELECT ON public.canonical_change_log TO authenticated;

CREATE OR REPLACE FUNCTION public.flowstate_can_read_workspace_v1(
  p_workspace_id uuid
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT (SELECT auth.uid()) IS NOT NULL
    AND p_workspace_id IS NOT NULL
    AND (
      EXISTS (
        SELECT 1 FROM public.workspaces AS workspace
        WHERE workspace.id = p_workspace_id
          AND workspace.owner_id = (SELECT auth.uid())
      )
      OR EXISTS (
        SELECT 1 FROM public.workspace_members AS member
        WHERE member.workspace_id = p_workspace_id
          AND member.user_id = (SELECT auth.uid())
      )
    )
$$;

REVOKE ALL ON FUNCTION public.flowstate_can_read_workspace_v1(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.flowstate_can_read_workspace_v1(uuid) TO authenticated;

DROP POLICY IF EXISTS canonical_change_log_select_scope
  ON public.canonical_change_log;
CREATE POLICY canonical_change_log_select_scope
  ON public.canonical_change_log
  FOR SELECT
  USING (
    (workspace_id IS NULL AND (SELECT auth.uid()) = user_id)
    OR (workspace_id IS NOT NULL AND public.flowstate_can_read_workspace_v1(workspace_id))
  );

CREATE OR REPLACE FUNCTION public.flowstate_can_write_workspace_v1(
  p_workspace_id uuid
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT (SELECT auth.uid()) IS NOT NULL
    AND p_workspace_id IS NOT NULL
    AND (
      EXISTS (
        SELECT 1
        FROM public.workspaces AS workspace
        WHERE workspace.id = p_workspace_id
          AND workspace.owner_id = (SELECT auth.uid())
      )
      OR EXISTS (
        SELECT 1
        FROM public.workspace_members AS member
        WHERE member.workspace_id = p_workspace_id
          AND member.user_id = (SELECT auth.uid())
          AND member.role IN ('owner', 'admin', 'member')
      )
    )
$$;

REVOKE ALL ON FUNCTION public.flowstate_can_write_workspace_v1(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.flowstate_can_write_workspace_v1(uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.flowstate_can_write_workspace_v1(uuid) TO authenticated;

-- Shared-workspace viewers remain readers. Legacy direct writers keep working
-- for owners, admins, and members until their caller cohort migrates to RPCs.
DROP POLICY IF EXISTS tasks_insert ON public.tasks;
CREATE POLICY tasks_insert
  ON public.tasks
  FOR INSERT
  WITH CHECK (
    (workspace_id IS NULL AND (SELECT auth.uid()) = user_id)
    OR (
      workspace_id IS NOT NULL
      AND (SELECT auth.uid()) = user_id
      AND public.flowstate_can_write_workspace_v1(workspace_id)
    )
  );

DROP POLICY IF EXISTS tasks_update ON public.tasks;
CREATE POLICY tasks_update
  ON public.tasks
  FOR UPDATE
  USING (
    (workspace_id IS NULL AND (SELECT auth.uid()) = user_id)
    OR (
      workspace_id IS NOT NULL
      AND public.flowstate_can_write_workspace_v1(workspace_id)
    )
  )
  WITH CHECK (
    (workspace_id IS NULL AND (SELECT auth.uid()) = user_id)
    OR (
      workspace_id IS NOT NULL
      AND public.flowstate_can_write_workspace_v1(workspace_id)
    )
  );

CREATE OR REPLACE FUNCTION public.flowstate_task_scope_immutable()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF (SELECT auth.uid()) IS NOT NULL
     AND (
       NEW.user_id IS DISTINCT FROM OLD.user_id
       OR NEW.workspace_id IS DISTINCT FROM OLD.workspace_id
     ) THEN
    RAISE EXCEPTION USING
      ERRCODE = '42501',
      MESSAGE = 'Task ownership and workspace scope require a typed domain command';
  END IF;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.flowstate_task_scope_immutable() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS flowstate_task_scope_immutable ON public.tasks;
CREATE TRIGGER flowstate_task_scope_immutable
BEFORE UPDATE ON public.tasks
FOR EACH ROW EXECUTE FUNCTION public.flowstate_task_scope_immutable();

DROP POLICY IF EXISTS tasks_delete ON public.tasks;
CREATE POLICY tasks_delete
  ON public.tasks
  FOR DELETE
  USING (
    (workspace_id IS NULL AND (SELECT auth.uid()) = user_id)
    OR (
      workspace_id IS NOT NULL
      AND public.flowstate_can_write_workspace_v1(workspace_id)
    )
  );

CREATE OR REPLACE FUNCTION public.flowstate_task_canonical_revision()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.canonical_revision := 1;
  ELSE
    NEW.canonical_revision := OLD.canonical_revision + 1;
  END IF;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.flowstate_task_canonical_revision() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS flowstate_task_canonical_revision ON public.tasks;
CREATE TRIGGER flowstate_task_canonical_revision
BEFORE INSERT OR UPDATE ON public.tasks
FOR EACH ROW EXECUTE FUNCTION public.flowstate_task_canonical_revision();

CREATE OR REPLACE FUNCTION public.flowstate_task_canonical_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_row public.tasks%ROWTYPE;
  v_owner uuid;
  v_actor uuid := (SELECT auth.uid());
  v_operation_id text := nullif(
    pg_catalog.current_setting('flowstate.canonical.operation_id', true),
    ''
  );
  v_source text := 'legacy';
  v_action text;
  v_revision bigint;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_row := OLD;
    v_action := 'deleted';
    v_revision := OLD.canonical_revision + 1;
  ELSE
    v_row := NEW;
    v_revision := NEW.canonical_revision;
    IF TG_OP = 'INSERT' THEN
      v_action := 'inserted';
    ELSIF OLD.is_deleted IS DISTINCT FROM NEW.is_deleted AND NEW.is_deleted THEN
      v_action := 'deleted';
    ELSIF OLD.is_deleted IS DISTINCT FROM NEW.is_deleted AND NOT NEW.is_deleted THEN
      v_action := 'restored';
    ELSE
      v_action := 'updated';
    END IF;
  END IF;

  v_owner := v_row.user_id;

  IF v_operation_id IS NOT NULL THEN
    SELECT operation.source
      INTO v_source
    FROM public.canonical_operations AS operation
    WHERE operation.user_id = v_actor
      AND operation.operation_id = v_operation_id
      AND operation.entity_type = 'task'
      AND operation.entity_id = v_row.id
      AND operation.state = 'applying';

    IF NOT FOUND THEN
      v_operation_id := NULL;
      v_source := 'legacy';
    END IF;
  END IF;

  INSERT INTO public.canonical_change_log (
    user_id,
    actor_user_id,
    workspace_id,
    entity_type,
    entity_id,
    action,
    canonical_revision,
    operation_id,
    source,
    tombstone,
    projection
  ) VALUES (
    v_owner,
    v_actor,
    v_row.workspace_id,
    'task',
    v_row.id,
    v_action,
    v_revision,
    v_operation_id,
    v_source,
    TG_OP = 'DELETE' OR COALESCE(v_row.is_deleted, false),
    pg_catalog.jsonb_build_object(
      'id', v_row.id,
      'title', v_row.title,
      'status', CASE WHEN v_row.status = 'done' THEN 'done' ELSE 'todo' END,
      'priority', v_row.priority,
      'dueDate', v_row.due_date,
      'progress', v_row.progress,
      'isDeleted', TG_OP = 'DELETE' OR COALESCE(v_row.is_deleted, false),
      'workspaceId', v_row.workspace_id
    )
  );

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.flowstate_task_canonical_change() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS flowstate_task_canonical_change ON public.tasks;
CREATE TRIGGER flowstate_task_canonical_change
AFTER INSERT OR UPDATE OR DELETE ON public.tasks
FOR EACH ROW EXECUTE FUNCTION public.flowstate_task_canonical_change();

CREATE OR REPLACE FUNCTION public.flowstate_patch_task_v1(
  p_operation_id text,
  p_contract_version text,
  p_source text,
  p_task_id text,
  p_base_revision bigint,
  p_patch jsonb,
  p_preview boolean DEFAULT true,
  p_preview_digest text DEFAULT NULL,
  p_preview_expires_at timestamptz DEFAULT NULL,
  p_workspace_id uuid DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_actor uuid := (SELECT auth.uid());
  v_task public.tasks%ROWTYPE;
  v_updated public.tasks%ROWTYPE;
  v_existing public.canonical_operations%ROWTYPE;
  v_issued_preview public.canonical_operation_previews%ROWTYPE;
  v_change_sequence bigint;
  v_normalized jsonb := '{}'::jsonb;
  v_unknown_keys text[];
  v_preview_expires_at timestamptz;
  v_expected_preview_digest text;
  v_request_hash text;
  v_scope_kind text;
  v_scope_id text;
  v_read_back jsonb;
  v_read_back_hash text;
  v_receipt jsonb;
  v_preview_found boolean := false;
  v_prior_operation_id text := pg_catalog.current_setting(
    'flowstate.canonical.operation_id',
    true
  );
BEGIN
  IF v_actor IS NULL THEN
    RETURN pg_catalog.jsonb_build_object(
      'ok', false,
      'result', 'rejected',
      'error', pg_catalog.jsonb_build_object(
        'code', 'not_authenticated',
        'message', 'Authentication is required'
      )
    );
  END IF;

  IF p_contract_version IS DISTINCT FROM 'task-v1'
     OR nullif(pg_catalog.btrim(p_operation_id), '') IS NULL
     OR pg_catalog.char_length(p_operation_id) > 160
     OR p_operation_id IS DISTINCT FROM pg_catalog.btrim(p_operation_id)
     OR p_preview IS NULL
     OR p_source IS NULL
     OR p_source !~ '^[a-z0-9][a-z0-9._:-]{0,63}$'
     OR nullif(pg_catalog.btrim(p_task_id), '') IS NULL
     OR p_base_revision IS NULL
     OR p_base_revision < 1
     OR p_patch IS NULL
     OR pg_catalog.jsonb_typeof(p_patch) <> 'object'
     OR p_patch = '{}'::jsonb THEN
    RETURN pg_catalog.jsonb_build_object(
      'ok', false,
      'result', 'rejected',
      'error', pg_catalog.jsonb_build_object(
        'code', 'invalid_request',
        'message', 'The canonical task request is invalid'
      )
    );
  END IF;

  SELECT pg_catalog.array_agg(key ORDER BY key)
    INTO v_unknown_keys
  FROM pg_catalog.jsonb_object_keys(p_patch) AS patch_key(key)
  WHERE key NOT IN ('title', 'description', 'priority', 'dueDate', 'progress');

  IF v_unknown_keys IS NOT NULL THEN
    RETURN pg_catalog.jsonb_build_object(
      'ok', false,
      'result', 'rejected',
      'error', pg_catalog.jsonb_build_object(
        'code', 'unsupported_patch',
        'message', 'The patch contains unsupported task fields',
        'fields', pg_catalog.to_jsonb(v_unknown_keys)
      )
    );
  END IF;

  IF p_patch ? 'title' THEN
    IF pg_catalog.jsonb_typeof(p_patch->'title') <> 'string'
       OR nullif(pg_catalog.btrim(p_patch->>'title'), '') IS NULL THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok', false, 'result', 'rejected',
        'error', pg_catalog.jsonb_build_object('code', 'invalid_title', 'message', 'title must be non-empty')
      );
    END IF;
    v_normalized := v_normalized || pg_catalog.jsonb_build_object('title', pg_catalog.btrim(p_patch->>'title'));
  END IF;

  IF p_patch ? 'description' THEN
    IF pg_catalog.jsonb_typeof(p_patch->'description') NOT IN ('string', 'null') THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok', false, 'result', 'rejected',
        'error', pg_catalog.jsonb_build_object('code', 'invalid_description', 'message', 'description must be text or null')
      );
    END IF;
    v_normalized := v_normalized || pg_catalog.jsonb_build_object('description', p_patch->'description');
  END IF;

  IF p_patch ? 'priority' THEN
    IF NOT (
      pg_catalog.jsonb_typeof(p_patch->'priority') = 'null'
      OR (
        pg_catalog.jsonb_typeof(p_patch->'priority') = 'string'
        AND p_patch->>'priority' IN ('low', 'medium', 'high')
      )
    ) THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok', false, 'result', 'rejected',
        'error', pg_catalog.jsonb_build_object('code', 'invalid_priority', 'message', 'priority is invalid')
      );
    END IF;
    v_normalized := v_normalized || pg_catalog.jsonb_build_object('priority', p_patch->'priority');
  END IF;

  IF p_patch ? 'dueDate' THEN
    IF pg_catalog.jsonb_typeof(p_patch->'dueDate') NOT IN ('string', 'null') THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok', false, 'result', 'rejected',
        'error', pg_catalog.jsonb_build_object('code', 'invalid_due_date', 'message', 'dueDate must be an ISO timestamp or null')
      );
    END IF;
    IF pg_catalog.jsonb_typeof(p_patch->'dueDate') = 'string'
       AND p_patch->>'dueDate' !~ '^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}(:\d{2}(\.\d{1,6})?)?(Z|[+-]\d{2}:\d{2})?)?$' THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok', false, 'result', 'rejected',
        'error', pg_catalog.jsonb_build_object('code', 'invalid_due_date', 'message', 'dueDate must be an ISO date or timestamp')
      );
    END IF;
    BEGIN
      IF pg_catalog.jsonb_typeof(p_patch->'dueDate') = 'string' THEN
        PERFORM (p_patch->>'dueDate')::timestamptz;
      END IF;
    EXCEPTION WHEN invalid_datetime_format OR datetime_field_overflow THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok', false, 'result', 'rejected',
        'error', pg_catalog.jsonb_build_object('code', 'invalid_due_date', 'message', 'dueDate must be an ISO timestamp or null')
      );
    END;
    v_normalized := v_normalized || pg_catalog.jsonb_build_object('dueDate', p_patch->'dueDate');
  END IF;

  IF p_patch ? 'progress' THEN
    IF pg_catalog.jsonb_typeof(p_patch->'progress') <> 'number'
       OR (p_patch->>'progress')::numeric <> pg_catalog.trunc((p_patch->>'progress')::numeric)
       OR (p_patch->>'progress')::numeric NOT BETWEEN 0 AND 100 THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok', false, 'result', 'rejected',
        'error', pg_catalog.jsonb_build_object('code', 'invalid_progress', 'message', 'progress must be an integer from 0 to 100')
      );
    END IF;
    v_normalized := v_normalized || pg_catalog.jsonb_build_object('progress', (p_patch->>'progress')::integer);
  END IF;

  v_request_hash := pg_catalog.encode(
    extensions.digest(
      pg_catalog.convert_to(
        pg_catalog.jsonb_build_object(
          'actorUserId', v_actor,
          'contractVersion', p_contract_version,
          'source', p_source,
          'taskId', p_task_id,
          'baseRevision', p_base_revision,
          'patch', v_normalized,
          'workspaceId', p_workspace_id
        )::text,
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );

  -- Serialize preview issuance and apply for one actor/operation identity.
  -- Different operations remain concurrent and are reconciled by row revision.
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(v_actor::text || ':' || p_operation_id, 0)
  );

  IF NOT p_preview THEN
    SELECT *
      INTO v_existing
    FROM public.canonical_operations AS operation
    WHERE operation.user_id = v_actor
      AND operation.operation_id = p_operation_id;

    IF FOUND THEN
      IF v_existing.request_hash IS DISTINCT FROM v_request_hash THEN
        RETURN pg_catalog.jsonb_build_object(
          'ok', false,
          'result', 'conflict',
          'error', pg_catalog.jsonb_build_object(
            'code', 'idempotency_conflict',
            'message', 'operationId was already used for another request'
          )
        );
      END IF;

      IF v_existing.state = 'committed' AND v_existing.canonical_result IS NOT NULL THEN
        RETURN pg_catalog.jsonb_build_object(
          'ok', true,
          'result', 'committed',
          'receipt', v_existing.canonical_result || pg_catalog.jsonb_build_object('replayed', true)
        );
      END IF;
    END IF;

    IF nullif(p_preview_digest, '') IS NULL OR p_preview_expires_at IS NULL THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok', false, 'result', 'conflict',
        'error', pg_catalog.jsonb_build_object('code', 'preview_mismatch', 'message', 'The approval does not match this request')
      );
    END IF;

    SELECT *
      INTO v_issued_preview
    FROM public.canonical_operation_previews AS issued
    WHERE issued.user_id = v_actor
      AND issued.operation_id = p_operation_id
      AND issued.preview_digest = p_preview_digest
    FOR UPDATE;
    v_preview_found := FOUND;

    IF v_preview_found AND v_issued_preview.consumed_at IS NOT NULL THEN
      SELECT *
        INTO v_existing
      FROM public.canonical_operations AS operation
      WHERE operation.user_id = v_actor
        AND operation.operation_id = p_operation_id;

      IF FOUND
         AND v_existing.request_hash = v_request_hash
         AND v_existing.state = 'committed'
         AND v_existing.canonical_result IS NOT NULL THEN
        RETURN pg_catalog.jsonb_build_object(
          'ok', true,
          'result', 'committed',
          'receipt', v_existing.canonical_result || pg_catalog.jsonb_build_object('replayed', true)
        );
      END IF;
    END IF;

    IF NOT v_preview_found
       OR v_issued_preview.request_hash IS DISTINCT FROM v_request_hash
       OR v_issued_preview.expires_at IS DISTINCT FROM p_preview_expires_at
       OR v_issued_preview.consumed_at IS NOT NULL THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok', false, 'result', 'conflict',
        'error', pg_catalog.jsonb_build_object('code', 'preview_mismatch', 'message', 'The approval does not match this request')
      );
    END IF;

    IF v_issued_preview.expires_at <= pg_catalog.clock_timestamp() THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok', false, 'result', 'conflict',
        'error', pg_catalog.jsonb_build_object('code', 'preview_expired', 'message', 'The approved preview has expired')
      );
    END IF;
  END IF;

  IF p_preview THEN
    SELECT *
      INTO v_task
    FROM public.tasks AS task
    WHERE task.id = p_task_id
      AND task.is_deleted = false;
  ELSE
    SELECT *
      INTO v_task
    FROM public.tasks AS task
    WHERE task.id = p_task_id
      AND task.is_deleted = false
    FOR UPDATE;
  END IF;

  IF NOT FOUND
     OR v_task.workspace_id IS DISTINCT FROM p_workspace_id
     OR (
       v_task.workspace_id IS NULL
       AND v_task.user_id IS DISTINCT FROM v_actor
     )
     OR (
       v_task.workspace_id IS NOT NULL
       AND NOT public.flowstate_can_write_workspace_v1(v_task.workspace_id)
     ) THEN
    RETURN pg_catalog.jsonb_build_object(
      'ok', false,
      'result', 'rejected',
      'error', pg_catalog.jsonb_build_object('code', 'not_found', 'message', 'Task was not found')
    );
  END IF;

  IF NOT p_preview THEN
    -- A same-operation caller may have committed while this transaction waited
    -- for the task row lock. Recheck before treating its base as stale.
    SELECT *
      INTO v_existing
    FROM public.canonical_operations AS operation
    WHERE operation.user_id = v_actor
      AND operation.operation_id = p_operation_id;

    IF FOUND THEN
      IF v_existing.request_hash IS DISTINCT FROM v_request_hash THEN
        RETURN pg_catalog.jsonb_build_object(
          'ok', false, 'result', 'conflict',
          'error', pg_catalog.jsonb_build_object('code', 'idempotency_conflict', 'message', 'operationId was already used for another request')
        );
      ELSIF v_existing.state = 'committed' AND v_existing.canonical_result IS NOT NULL THEN
        RETURN pg_catalog.jsonb_build_object(
          'ok', true,
          'result', 'committed',
          'receipt', v_existing.canonical_result || pg_catalog.jsonb_build_object('replayed', true)
        );
      END IF;
    END IF;
  END IF;

  IF v_task.canonical_revision IS DISTINCT FROM p_base_revision THEN
    RETURN pg_catalog.jsonb_build_object(
      'ok', false,
      'result', 'conflict',
      'error', pg_catalog.jsonb_build_object(
        'code', 'stale_revision',
        'message', 'Task changed after the requested base revision',
        'currentRevision', v_task.canonical_revision
      )
    );
  END IF;

  v_read_back := pg_catalog.jsonb_build_object(
    'id', v_task.id,
    'title', v_task.title,
    'description', v_task.description,
    'priority', v_task.priority,
    'dueDate', v_task.due_date,
    'progress', v_task.progress,
    'status', CASE WHEN v_task.status = 'done' THEN 'done' ELSE 'todo' END,
    'isDeleted', v_task.is_deleted,
    'workspaceId', v_task.workspace_id,
    'canonicalRevision', v_task.canonical_revision,
    'canonicalUpdatedAt', v_task.updated_at
  );

  IF p_preview THEN
    IF EXISTS (
      SELECT 1
      FROM public.canonical_operations AS operation
      WHERE operation.user_id = v_actor
        AND operation.operation_id = p_operation_id
    ) THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok', false, 'result', 'conflict',
        'error', pg_catalog.jsonb_build_object('code', 'idempotency_conflict', 'message', 'operationId was already applied')
      );
    END IF;

    SELECT *
      INTO v_issued_preview
    FROM public.canonical_operation_previews AS issued
    WHERE issued.user_id = v_actor
      AND issued.operation_id = p_operation_id
    FOR UPDATE;

    IF FOUND THEN
      IF v_issued_preview.request_hash IS DISTINCT FROM v_request_hash THEN
        RETURN pg_catalog.jsonb_build_object(
          'ok', false, 'result', 'conflict',
          'error', pg_catalog.jsonb_build_object('code', 'idempotency_conflict', 'message', 'operationId already has another preview')
        );
      END IF;

      IF v_issued_preview.consumed_at IS NOT NULL
         OR v_issued_preview.expires_at <= pg_catalog.clock_timestamp() THEN
        RETURN pg_catalog.jsonb_build_object(
          'ok', false, 'result', 'conflict',
          'error', pg_catalog.jsonb_build_object('code', 'preview_expired', 'message', 'Use a new operationId for a fresh preview')
        );
      END IF;

      v_expected_preview_digest := v_issued_preview.preview_digest;
      v_preview_expires_at := v_issued_preview.expires_at;
    ELSE
      v_preview_expires_at := pg_catalog.clock_timestamp() + interval '15 minutes';
      v_expected_preview_digest := pg_catalog.encode(
        extensions.gen_random_bytes(32),
        'hex'
      );

      INSERT INTO public.canonical_operation_previews (
        user_id,
        operation_id,
        preview_digest,
        request_hash,
        expires_at
      ) VALUES (
        v_actor,
        p_operation_id,
        v_expected_preview_digest,
        v_request_hash,
        v_preview_expires_at
      );
    END IF;

    RETURN pg_catalog.jsonb_build_object(
      'ok', true,
      'result', 'preview',
      'contractVersion', p_contract_version,
      'operationId', p_operation_id,
      'baseRevision', p_base_revision,
      'previewDigest', v_expected_preview_digest,
      'previewExpiresAt', v_preview_expires_at,
      'normalizedPayload', v_normalized,
      'readBack', v_read_back
    );
  END IF;

  v_scope_kind := CASE WHEN v_task.workspace_id IS NULL THEN 'personal' ELSE 'workspace' END;
  v_scope_id := COALESCE(v_task.workspace_id::text, v_actor::text);

  INSERT INTO public.canonical_operations (
    user_id,
    operation_id,
    contract_version,
    source,
    scope_kind,
    scope_id,
    workspace_id,
    entity_type,
    action,
    entity_id,
    request_hash,
    state
  ) VALUES (
    v_actor,
    p_operation_id,
    p_contract_version,
    p_source,
    v_scope_kind,
    v_scope_id,
    v_task.workspace_id,
    'task',
    'patch',
    v_task.id,
    v_request_hash,
    'applying'
  )
  ON CONFLICT (user_id, operation_id) DO NOTHING;

  IF NOT FOUND THEN
    SELECT *
      INTO STRICT v_existing
    FROM public.canonical_operations AS operation
    WHERE operation.user_id = v_actor
      AND operation.operation_id = p_operation_id
    FOR UPDATE;

    IF v_existing.request_hash IS DISTINCT FROM v_request_hash THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok', false, 'result', 'conflict',
        'error', pg_catalog.jsonb_build_object('code', 'idempotency_conflict', 'message', 'operationId was already used for another request')
      );
    END IF;

    IF v_existing.state = 'committed' AND v_existing.canonical_result IS NOT NULL THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok', true,
        'result', 'committed',
        'receipt', v_existing.canonical_result || pg_catalog.jsonb_build_object('replayed', true)
      );
    END IF;
  END IF;

  UPDATE public.canonical_operation_previews AS issued
  SET
    consumed_at = pg_catalog.clock_timestamp(),
    updated_at = pg_catalog.clock_timestamp()
  WHERE issued.user_id = v_actor
    AND issued.operation_id = p_operation_id
    AND issued.preview_digest = p_preview_digest
    AND issued.consumed_at IS NULL;

  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object(
      'ok', false, 'result', 'conflict',
      'error', pg_catalog.jsonb_build_object('code', 'preview_mismatch', 'message', 'The approval was already consumed')
    );
  END IF;

  PERFORM pg_catalog.set_config('flowstate.canonical.operation_id', p_operation_id, true);

  UPDATE public.tasks AS task
  SET
    title = CASE
      WHEN v_normalized ? 'title' THEN v_normalized->>'title'
      ELSE task.title
    END,
    description = CASE
      WHEN v_normalized ? 'description' AND pg_catalog.jsonb_typeof(v_normalized->'description') = 'null' THEN NULL
      WHEN v_normalized ? 'description' THEN v_normalized->>'description'
      ELSE task.description
    END,
    priority = CASE
      WHEN v_normalized ? 'priority' AND pg_catalog.jsonb_typeof(v_normalized->'priority') = 'null' THEN NULL
      WHEN v_normalized ? 'priority' THEN v_normalized->>'priority'
      ELSE task.priority
    END,
    due_date = CASE
      WHEN v_normalized ? 'dueDate' AND pg_catalog.jsonb_typeof(v_normalized->'dueDate') = 'null' THEN NULL
      WHEN v_normalized ? 'dueDate' THEN (v_normalized->>'dueDate')::timestamptz
      ELSE task.due_date
    END,
    progress = CASE
      WHEN v_normalized ? 'progress' THEN (v_normalized->>'progress')::integer
      ELSE task.progress
    END
  WHERE task.id = v_task.id
  RETURNING task.* INTO STRICT v_updated;

  PERFORM pg_catalog.set_config(
    'flowstate.canonical.operation_id',
    COALESCE(v_prior_operation_id, ''),
    true
  );

  SELECT change.change_sequence
    INTO STRICT v_change_sequence
  FROM public.canonical_change_log AS change
  WHERE change.actor_user_id = v_actor
    AND change.operation_id = p_operation_id
    AND change.entity_type = 'task'
    AND change.entity_id = v_updated.id
  ORDER BY change.change_sequence DESC
  LIMIT 1;

  v_read_back := pg_catalog.jsonb_build_object(
    'id', v_updated.id,
    'title', v_updated.title,
    'description', v_updated.description,
    'priority', v_updated.priority,
    'dueDate', v_updated.due_date,
    'progress', v_updated.progress,
    'status', CASE WHEN v_updated.status = 'done' THEN 'done' ELSE 'todo' END,
    'isDeleted', v_updated.is_deleted,
    'workspaceId', v_updated.workspace_id,
    'canonicalRevision', v_updated.canonical_revision,
    'canonicalUpdatedAt', v_updated.updated_at
  );

  v_read_back_hash := pg_catalog.encode(
    extensions.digest(
      pg_catalog.convert_to(v_read_back::text, 'UTF8'),
      'sha256'
    ),
    'hex'
  );

  v_receipt := pg_catalog.jsonb_build_object(
    'contractVersion', p_contract_version,
    'operationId', p_operation_id,
    'source', p_source,
    'entityType', 'task',
    'action', 'patch',
    'entityId', v_updated.id,
    'canonicalRevision', v_updated.canonical_revision,
    'canonicalUpdatedAt', v_updated.updated_at,
    'changeSequence', v_change_sequence,
    'replayed', false,
    'committedAt', pg_catalog.clock_timestamp(),
    'readBack', v_read_back,
    'readBackHash', v_read_back_hash
  );

  UPDATE public.canonical_operations AS operation
  SET
    state = 'committed',
    canonical_revision = v_updated.canonical_revision,
    change_sequence = v_change_sequence,
    canonical_result = v_receipt,
    committed_at = (v_receipt->>'committedAt')::timestamptz,
    updated_at = pg_catalog.clock_timestamp()
  WHERE operation.user_id = v_actor
    AND operation.operation_id = p_operation_id;

  RETURN pg_catalog.jsonb_build_object(
    'ok', true,
    'result', 'committed',
    'receipt', v_receipt
  );
END;
$$;

REVOKE ALL ON FUNCTION public.flowstate_patch_task_v1(
  text, text, text, text, bigint, jsonb, boolean, text, timestamptz, uuid
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.flowstate_patch_task_v1(
  text, text, text, text, bigint, jsonb, boolean, text, timestamptz, uuid
) FROM anon;
GRANT EXECUTE ON FUNCTION public.flowstate_patch_task_v1(
  text, text, text, text, bigint, jsonb, boolean, text, timestamptz, uuid
) TO authenticated;

COMMENT ON TABLE public.canonical_operations IS
  'User-scoped exactly-once operation ledger. A committed row stores its replayable canonical receipt.';
COMMENT ON TABLE public.canonical_change_log IS
  'RLS-filtered durable change cursor. Global sequence gaps are expected after user/workspace filtering.';
COMMENT ON FUNCTION public.flowstate_patch_task_v1(
  text, text, text, text, bigint, jsonb, boolean, text, timestamptz, uuid
) IS
  'Preview/apply a bounded task patch and return a durable, read-back-verifiable canonical receipt.';
